database_connection_string: "sqlite:///db.sqlite3"

port: 8787
host: '0'

ntu_user: "b08902000"
ntu_pass: "123456789"

telegram_bot_token: "123456789:your-bot-token"
telegram_chat_id: "987654321"

crawler_list:
 - CeibaCrawler
 - NTUCoolCrawler
